version: '3.8'
services:
  backend:
    build: 
      context: ./backend
      target: base
    volumes:
      - ./backend:/usr/src/app
    ports:
      - '5000:5000'
    depends_on:
      - db
    command: npm run start:dev

  frontend:
    build: 
      context: ./frontend
      target: base
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - db
      - backend
    command: npm run dev

  db:
    image: postgres:14
    restart: always
    volumes:
      - 'postgres_data:/var/lib/postgresql/data/'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  prisma-studio:
    container_name: prisma-studio
    image: timothyjmiller/prisma-studio:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5555:5555
    depends_on:
      - db

volumes:
  postgres_data:
