version: "3"
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: "j3ns6/competition-platform-backend"
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: "j3ns6/competition-platform-frontend"
    volumes: 
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - backend

  db:
    image: postgres:14
    restart: always
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'
    environment:
      POSTGRES_PASSWORD: 04DhXV!SyOL

volumes:
  pgdata: {}
