version: '3'
services:
  backend:
    build: ./backend
    volumes:
      - backend:./backend:/usr/src/app
    ports:
      - '5000:5000'
    depends_on:
      - db
    command: 
      - npm run start:dev

  frontend:
    build: ./frontend
    volumes:
      - frontend:./frontend:/usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - db
      - backend

  db:
    image: postgres:14
    restart: always
    volumes:
      - 'postgres_data:/var/lib/postgresql/data/'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  postgres-adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080

volumes:
  backend:
  frontend:
  postgres_data: