name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'api-imagechase'
          heroku_email: 'jonasoliver@web.de'
          usedocker: true
          appdir: 'backend'
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'imagecompetition'
          heroku_email: 'jonasoliver@web.de'
          usedocker: true
          appdir: 'frontend'
